name: Build and Deploy

on: [push]

env:
  #DOCKER_DRIVER: overlay2
  CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
  CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  CI_PROJECT_NAME: hash_flask

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.CI_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.CI_REGISTRY_USER }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t klementus/${{ env.CI_PROJECT_NAME }}:latest .
          docker push klementus/${{ env.CI_PROJECT_NAME }}:latest
        env:
          CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
          CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    needs: build

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          docker login -u '${{ secrets.CI_REGISTRY_USER }}' -p '${{ secrets.CI_REGISTRY_PASSWORD }}'
          docker pull klementus/${{ env.CI_PROJECT_NAME }}:latest
          docker stop flask || true
          docker rm flask || true
          docker run -d -p 4022:4022 --name flask klementus/${{ env.CI_PROJECT_NAME }}:latest
          images=\$(docker images -f 'dangling=true' -q)
          if [ -n \"\$images\" ]; then
            docker rmi -f \$images
          fi"
